branch-defaults:
  pipeline:
    environment: tausi-app-dev-env
environment-defaults:
  tausi-app-dev-env:
    branch: null
    repository: null
global:
  application_name: tausi_app
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
